require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  CacheRootDirectory: tmp/cache
  TargetRubyVersion: 2.6.5
  Exclude:
    - tmp/bundle/**/*
  Include:
    - '**/*.rb'
    - '**/*.rake'
    - Gemfile
    - Rakefile
    - '*.gemspec'

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - tasks/**/*
    - '*.gemspec'

Metrics/LineLength:
  Max: 100

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

Style/AsciiComments:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/ModuleFunction:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
